./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 2 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 3 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 4 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 5 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 6 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 7 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 8 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 9 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 10 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 11-o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 12 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 13 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 14 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 15 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 16 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 17 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 18 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 19 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 20 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 21-o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 22 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 23 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 24 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 25 -o "output/"
./gomanga -s "manytoon" -m "my-friend-came-back-from-the-future-to-fuck-me-toon0006" -c 26 -o "output/"